apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluent-bit
  namespace: logging
  labels:
    app: fluent-bit
spec:
  selector:
    matchLabels:
      app: fluent-bit
  template:
    metadata:
      labels:
        app: fluent-bit
    spec:
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 30
      tolerations:
        - operator: Exists

      containers:
        - name: fluent-bit
          image: public.ecr.aws/aws-observability/aws-for-fluent-bit:latest
          imagePullPolicy: Always

          command:
            - /fluent-bit/bin/fluent-bit
          args:
            - -c
            - /fluent-bit/etc/fluent-bit.conf

          ports:
            - name: http
              containerPort: 2020

          env:
            - name: AWS_REGION
              value: "eu-north-1"

            # AWS credentials from secret (required for self-hosted k3s)
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: fluentbit-aws-creds
                  key: aws_access_key_id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: fluentbit-aws-creds
                  key: aws_secret_access_key

            # Kubernetes metadata filter envs
            - name: KUBE_URL
              value: "https://kubernetes.default.svc:443"
            - name: KUBE_CA_FILE
              value: "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt"
            - name: KUBE_TOKEN_FILE
              value: "/var/run/secrets/kubernetes.io/serviceaccount/token"

          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 500Mi

          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true

            - name: config
              mountPath: /fluent-bit/etc/
              readOnly: true

            - name: storage
              mountPath: /fluent-bit/storage

            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true

      volumes:
        - name: varlog
          hostPath:
            path: /var/log

        - name: config
          configMap:
            name: fluent-bit-config

        - name: storage
          hostPath:
            path: /var/fluent-bit
            type: DirectoryOrCreate

        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
